# Template: Semgrep SAST workflow
# To enable: move this file to `.github/workflows/semgrep-scan.yml` in the repo (or copy its contents to that path).

name: "SAST: Semgrep"

on:
  pull_request: {}

jobs:
  semgrep:
    name: Semgrep (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install --upgrade semgrep

      - name: Run Semgrep
        run: semgrep --config=p/ci --json -o semgrep-report.json . || true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json
